... 
null_3 address.java null_1 used null_2 receivers null_3 ...
null_1 read from null_1 addressbook 
null_3 checks null_1 validating we 
expect correct entries validating null_1 addressbook null_1 ...
null_2 scope null_2 project.there null_2 setters null_1 ...
set null_1 values addressbook.java contains
...